export const services = {
  ele: {
    slug: 'elektricke-zariadenia',
    color: '#00d4ff',
    colorVar: 'ele',
    tag: 'Elektrické zariadenia',
    icon: '⚡',
    title: 'Revízia elektrickej inštalácie, bleskozvodu a spotrebičov',
    desc: 'Odborné prehliadky a odborné skúšky elektrických zariadení podľa vyhlášky č. 508/2009 Z. z. Východiskové aj periodické revízie na celom Slovensku.',
    cardDesc: 'Revízie elektrickej inštalácie, bleskozvodov, spotrebičov a elektrického náradia.',
    cardItems: ['Revízia elektrickej inštalácie', 'Revízia bleskozvodu', 'Revízia elektrických spotrebičov', 'Revízia el. ručného náradia', 'Východisková aj periodická revízia'],
    sectionTitle: 'Kedy potrebujete revíziu elektriky?',
    text1: 'Máte dom, byt, firmu alebo prevádzku? Zo zákona musíte mať pravidelnú revíziu elektrickej inštalácie. Lehoty sa líšia podľa typu prostredia — v bežnom byte je to každých 5 rokov, v prevádzke to môže byť aj každé 2 roky. Ak ste robili novú elektroinštaláciu alebo rekonštrukciu, potrebujete východiskovú revíziu ešte pred prvým zapojením.',
    text2: 'To isté platí pre bleskozvod — ak máte na streche hromozvod, musíte mať jeho revíziu. Bez nej vám poisťovňa v prípade zásahu bleskom nepreplatí škodu.',
    list: [
      'Východisková revízia novej alebo rekonštruovanej inštalácie',
      'Periodická revízia podľa lehôt vyhlášky 508/2009 Z. z.',
      'Revízia bleskozvodu (hromozvodu) podľa STN 62305',
      'Revízia elektrických spotrebičov podľa STN 33 1630',
      'Revízia el. ručného náradia podľa STN 33 1630',
      'Kompletná revízna správa s protokolom o meraní',
    ],
    items: [
      { icon: '🏠', text: 'Byty a rodinné domy', badge: 'každých 5 rokov' },
      { icon: '🏢', text: 'Kancelárie a obchody', badge: 'každých 5 rokov' },
      { icon: '🏭', text: 'Výrobné prevádzky', badge: 'každé 2-3 roky' },
      { icon: '⚡', text: 'Priestory s nebezp. výbuchu', badge: 'každé 2 roky' },
      { icon: '🔨', text: 'Stavenisko', badge: 'každých 6 mesiacov' },
    ],
  },
  plyn: {
    slug: 'plynove-zariadenia',
    color: '#ff2d6b',
    colorVar: 'plyn',
    tag: 'Plynové zariadenia',
    icon: '🔥',
    title: 'Revízia plynového kotla, rozvodov a spotrebičov',
    desc: 'Odborné prehliadky a odborné skúšky plynových zariadení. Kotly, rozvody, komíny, regulačné stanice — všetko podľa vyhlášky č. 508/2009 Z. z. Platí pre zariadenia spadajúce do skupiny A, B alebo C podľa prílohy č. 1.',
    cardDesc: 'Revízie plynových kotlov, rozvodov, spotrebičov a komínov. Aby ste vedeli, že je u vás všetko bezpečné.',
    cardItems: ['Revízia plynového kotla', 'Revízia plynových rozvodov', 'Revízia plynových spotrebičov', 'Kontrola komína a dymovodu', 'Odborná prehliadka kotolne'],
    sectionTitle: 'Prečo je revízia plynu taká dôležitá?',
    text1: 'Máte doma plynový kotol? Potom by ste mali vedieť, že odborná prehliadka (kontrola) sa robí každý rok a odborná skúška (revízia) každé tri roky. Platí to pre všetky plynové spotrebiče — kotly, ohrievače vody, sporáky s výkonom od 5 kW, plynové rozvody aj regulačné stanice.',
    text2: 'Nejde len o papier do šuflíka. Ide o bezpečnosť vašej rodiny. Unikajúci plyn alebo nefunkčný odvod spalín môžu mať fatálne následky.',
    list: [
      'Odborná prehliadka plynového kotla — každý rok',
      'Odborná skúška plynového zariadenia — každé 3 roky',
      'Revízia plynových rozvodov a prípojok',
      'Kontrola odvodu spalín (komín, dymovod)',
      'Revízia kotolní a regulačných staníc plynu',
      'Tlaková skúška plynovodu pri novej inštalácii',
    ],
    items: [
      { icon: '🔥', text: 'Plynový kotol (od 5 kW)', badge: 'kontrola 1r / skúška 3r' },
      { icon: '🚿', text: 'Plynový ohrievač vody', badge: 'kontrola 1r / skúška 3r' },
      { icon: '🔧', text: 'Plynový rozvod', badge: 'kontrola 1r / skúška 3r' },
      { icon: '🏭', text: 'Kotolňa (nad 0,5 MW)', badge: 'skupina A — úradná skúška' },
      { icon: '📋', text: 'Regulačná stanica', badge: 'kontrola 1r / skúška 3r' },
    ],
  },
  tlak: {
    slug: 'tlakove-zariadenia',
    color: '#8b5cf6',
    colorVar: 'tlak',
    tag: 'Tlakové zariadenia',
    icon: '⚙️',
    title: 'Revízia tlakových nádob, kompresorov a kotlov',
    desc: 'Vonkajšie prehliadky, vnútorné prehliadky a tlakové skúšky. Kompletné revízie tlakových zariadení skupiny A, B aj C.',
    cardDesc: 'Revízie tlakových nádob, kompresorov, expanzných nádob a kotlov.',
    cardItems: ['Revízia tlakovej nádoby', 'Revízia kompresora', 'Revízia expanznej nádoby', 'Parné a kvapalinové kotly', 'Vonkajšia + vnútorná + tlaková skúška'],
    sectionTitle: 'Čo všetko patrí medzi tlakové zariadenia?',
    text1: 'Tlakové zariadenia sú všade — kompresory v dielňach, expanzné nádoby v kotolniach, tlakové nádoby v priemysle, parné kotly vo výrobe. Podľa vyhlášky 508/2009 Z. z. sa delia do skupín A, B a C podľa miery ohrozenia.',
    text2: 'Robíme vonkajšie prehliadky, vnútorné prehliadky aj tlakové skúšky. Po revízii dostanete kompletnú revíznu správu so všetkými náležitosťami.',
    list: [
      'Vonkajšia prehliadka tlakovej nádoby',
      'Vnútorná prehliadka tlakovej nádoby',
      'Tlaková skúška',
      'Revízia kompresora a vzdušníka',
      'Revízia expanznej nádoby',
      'Revízia parných a kvapalinových kotlov (trieda I.–V.)',
    ],
    items: [
      { icon: '🔩', text: 'Tlaková nádoba sk. A', badge: 'VP 1r / VnP 3r / TS 9r' },
      { icon: '🔧', text: 'Tlaková nádoba sk. B', badge: 'VP 1r / VnP+TS 5r' },
      { icon: '💨', text: 'Kompresor + vzdušník', badge: 'podľa skupiny nádoby' },
      { icon: '♨️', text: 'Parný kotol (I.–IV. trieda)', badge: 'VP 3m–1r / VnP+TS 1–9r' },
      { icon: '🌡️', text: 'Kvapalinový kotol (V. trieda)', badge: 'VP 1r / VnP 3r' },
    ],
  },
  zdvih: {
    slug: 'zdvihacie-zariadenia',
    color: '#00e676',
    colorVar: 'zdvih',
    tag: 'Zdvíhacie zariadenia',
    icon: '🏗️',
    title: 'Revízia žeriavov, plošín, brán a vozíkov',
    desc: 'Odborné prehliadky a skúšky zdvíhacích zariadení vrátane viazacích prostriedkov. Od žeriavov cez priemyselné brány po vysokozdvižné vozíky.',
    cardDesc: 'Revízie žeriavov, plošín, priemyselných brán, autozdvihákov, vysokozdvižných vozíkov a viazacích prostriedkov.',
    cardItems: ['Revízia žeriavu', 'Revízia zdvíhacej plošiny', 'Revízia priemyselných brán', 'Revízia autozdviháka', 'Revízia vysokozdvižného vozíka', 'Kontrola viazacích prostriedkov'],
    sectionTitle: 'Prečo sú revízie zdvíhacích zariadení také dôležité?',
    text1: 'Zdvíhacie zariadenia sú jedny z najrizikovejších technických zariadení — pracujú s ťažkými bremenami a akákoľvek porucha môže mať vážne následky. Medzi VTZ zdvíhacie patria aj zvislé posuvné brány s motorovým pohonom v priemyselných halách, skladoch a logistických centrách.',
    text2: 'Okrem samotných zariadení kontrolujeme aj viazacie prostriedky — laná, reťaze, popruhy a háky.',
    list: [
      'Odborná prehliadka a skúška žeriavov a žeriavových dráh',
      'Revízia zdvíhacích plošín a servisných zdvíhacích zariadení',
      'Revízia zvislých posuvných brán s motorovým pohonom',
      'Revízia autozdvihákov (hydraulický zdvihák na vozidlá)',
      'Revízia vysokozdvižných a nízkozdvižných vozíkov',
      'Kontrola viazacích prostriedkov (laná, reťaze, popruhy)',
      'Revízia stavebných výťahov a pohyblivých plošín',
    ],
    items: [
      { icon: '🏗️', text: 'Žeriav nad 1 000 kg (sk. A)', badge: 'OP 1r / OS 2r' },
      { icon: '🚪', text: 'Priemyselná brána s mot. pohonom', badge: 'lehoty podľa výrobcu' },
      { icon: '📐', text: 'Zdvíhacia plošina', badge: 'OP 3m / OS 1r' },
      { icon: '🔧', text: 'Autozdvihák (hydraulický)', badge: 'OP 1r / OS podľa výrobcu' },
      { icon: '🚜', text: 'Vysokozdvižný vozík', badge: 'OP 6m / OS 1r' },
      { icon: '🔗', text: 'Viazacie prostriedky', badge: 'kontrola pred použitím' },
    ],
  },
} as const;

export type ServiceKey = keyof typeof services;
